---
apiVersion: v1
kind: Secret
metadata:
  name: DevConf-IDP-poi-backend-app-repo
  namespace: janus-argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: https://github.com/DevConf-IDP/NAMESPACE-backend-gitops
